name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  animated_gesture_detector: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  go_router: ^6.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
